//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.3.0
//     from Assets/Input/PlayerControls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @PlayerControls : IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @PlayerControls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""PlayerControls"",
    ""maps"": [
        {
            ""name"": ""player"",
            ""id"": ""d563844b-5b04-4dd8-af2b-98699229c4f6"",
            ""actions"": [
                {
                    ""name"": ""hotbar1"",
                    ""type"": ""PassThrough"",
                    ""id"": ""dfb26098-6ace-4244-bfad-88af7e31d3f6"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar2"",
                    ""type"": ""PassThrough"",
                    ""id"": ""0154bcfb-946e-4055-b00e-7f17cee0e583"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar3"",
                    ""type"": ""PassThrough"",
                    ""id"": ""98581ea7-cda5-493c-96b0-94dd1c9df26e"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar4"",
                    ""type"": ""PassThrough"",
                    ""id"": ""1ad22f6c-49f0-46ab-b6f0-914df8c4b755"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar5"",
                    ""type"": ""PassThrough"",
                    ""id"": ""5e85896b-ba4a-4980-9f6b-72287d6b9a32"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar6"",
                    ""type"": ""PassThrough"",
                    ""id"": ""e311cea7-d522-4269-8355-9d8dc9d3ec9d"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar7"",
                    ""type"": ""PassThrough"",
                    ""id"": ""853c4b38-1421-4d63-adbc-2427fbb3bd74"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar8"",
                    ""type"": ""PassThrough"",
                    ""id"": ""6d7e07d9-c889-428a-8154-deaac8d03e35"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""hotbar9"",
                    ""type"": ""PassThrough"",
                    ""id"": ""a4b1f097-be3f-4973-a3e2-a874f200d42f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""mousewheel"",
                    ""type"": ""PassThrough"",
                    ""id"": ""fe8d5421-0802-45cc-858e-416bb075dad6"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""useitem"",
                    ""type"": ""Button"",
                    ""id"": ""954efae5-8e4e-4e5c-93ac-542d8f081d9f"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""2595c512-6867-4c16-9d1c-f186c8197740"",
                    ""path"": ""<Keyboard>/1"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar1"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""512997fe-ef2a-4451-b1f9-d51994ac57b8"",
                    ""path"": ""<Keyboard>/2"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar2"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""155b5d56-3faa-4f36-bee0-a723fe30c855"",
                    ""path"": ""<Keyboard>/3"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar3"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""7e6349ab-48a5-49f0-8a75-e79aa5992fc2"",
                    ""path"": ""<Keyboard>/4"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar4"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1f5c733d-6283-4733-bda2-add051c5bc9c"",
                    ""path"": ""<Keyboard>/5"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar5"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f1a6f6e7-a2f9-431f-b893-ff2619350dac"",
                    ""path"": ""<Keyboard>/6"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar6"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""5c70fb6d-0ecb-46f1-ad51-d517c698b087"",
                    ""path"": ""<Keyboard>/7"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar7"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""82817f45-e390-480c-8819-5477aa1cc95b"",
                    ""path"": ""<Keyboard>/8"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar8"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""108d7e5f-931e-4919-b3a1-e2cd4322aeeb"",
                    ""path"": ""<Keyboard>/9"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""hotbar9"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""25c360ef-0e56-41d5-8dd6-2dff3bb4d6e2"",
                    ""path"": ""<Mouse>/scroll/y"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""mousewheel"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""716aa026-3e56-47ad-a0a7-48806e4fdb91"",
                    ""path"": ""<Mouse>/leftButton"",
                    ""interactions"": ""Press"",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""useitem"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // player
        m_player = asset.FindActionMap("player", throwIfNotFound: true);
        m_player_hotbar1 = m_player.FindAction("hotbar1", throwIfNotFound: true);
        m_player_hotbar2 = m_player.FindAction("hotbar2", throwIfNotFound: true);
        m_player_hotbar3 = m_player.FindAction("hotbar3", throwIfNotFound: true);
        m_player_hotbar4 = m_player.FindAction("hotbar4", throwIfNotFound: true);
        m_player_hotbar5 = m_player.FindAction("hotbar5", throwIfNotFound: true);
        m_player_hotbar6 = m_player.FindAction("hotbar6", throwIfNotFound: true);
        m_player_hotbar7 = m_player.FindAction("hotbar7", throwIfNotFound: true);
        m_player_hotbar8 = m_player.FindAction("hotbar8", throwIfNotFound: true);
        m_player_hotbar9 = m_player.FindAction("hotbar9", throwIfNotFound: true);
        m_player_mousewheel = m_player.FindAction("mousewheel", throwIfNotFound: true);
        m_player_useitem = m_player.FindAction("useitem", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }
    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // player
    private readonly InputActionMap m_player;
    private IPlayerActions m_PlayerActionsCallbackInterface;
    private readonly InputAction m_player_hotbar1;
    private readonly InputAction m_player_hotbar2;
    private readonly InputAction m_player_hotbar3;
    private readonly InputAction m_player_hotbar4;
    private readonly InputAction m_player_hotbar5;
    private readonly InputAction m_player_hotbar6;
    private readonly InputAction m_player_hotbar7;
    private readonly InputAction m_player_hotbar8;
    private readonly InputAction m_player_hotbar9;
    private readonly InputAction m_player_mousewheel;
    private readonly InputAction m_player_useitem;
    public struct PlayerActions
    {
        private @PlayerControls m_Wrapper;
        public PlayerActions(@PlayerControls wrapper) { m_Wrapper = wrapper; }
        public InputAction @hotbar1 => m_Wrapper.m_player_hotbar1;
        public InputAction @hotbar2 => m_Wrapper.m_player_hotbar2;
        public InputAction @hotbar3 => m_Wrapper.m_player_hotbar3;
        public InputAction @hotbar4 => m_Wrapper.m_player_hotbar4;
        public InputAction @hotbar5 => m_Wrapper.m_player_hotbar5;
        public InputAction @hotbar6 => m_Wrapper.m_player_hotbar6;
        public InputAction @hotbar7 => m_Wrapper.m_player_hotbar7;
        public InputAction @hotbar8 => m_Wrapper.m_player_hotbar8;
        public InputAction @hotbar9 => m_Wrapper.m_player_hotbar9;
        public InputAction @mousewheel => m_Wrapper.m_player_mousewheel;
        public InputAction @useitem => m_Wrapper.m_player_useitem;
        public InputActionMap Get() { return m_Wrapper.m_player; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PlayerActions set) { return set.Get(); }
        public void SetCallbacks(IPlayerActions instance)
        {
            if (m_Wrapper.m_PlayerActionsCallbackInterface != null)
            {
                @hotbar1.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar1;
                @hotbar1.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar1;
                @hotbar1.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar1;
                @hotbar2.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar2;
                @hotbar2.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar2;
                @hotbar2.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar2;
                @hotbar3.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar3;
                @hotbar3.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar3;
                @hotbar3.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar3;
                @hotbar4.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar4;
                @hotbar4.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar4;
                @hotbar4.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar4;
                @hotbar5.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar5;
                @hotbar5.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar5;
                @hotbar5.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar5;
                @hotbar6.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar6;
                @hotbar6.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar6;
                @hotbar6.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar6;
                @hotbar7.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar7;
                @hotbar7.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar7;
                @hotbar7.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar7;
                @hotbar8.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar8;
                @hotbar8.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar8;
                @hotbar8.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar8;
                @hotbar9.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar9;
                @hotbar9.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar9;
                @hotbar9.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnHotbar9;
                @mousewheel.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousewheel;
                @mousewheel.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousewheel;
                @mousewheel.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnMousewheel;
                @useitem.started -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseitem;
                @useitem.performed -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseitem;
                @useitem.canceled -= m_Wrapper.m_PlayerActionsCallbackInterface.OnUseitem;
            }
            m_Wrapper.m_PlayerActionsCallbackInterface = instance;
            if (instance != null)
            {
                @hotbar1.started += instance.OnHotbar1;
                @hotbar1.performed += instance.OnHotbar1;
                @hotbar1.canceled += instance.OnHotbar1;
                @hotbar2.started += instance.OnHotbar2;
                @hotbar2.performed += instance.OnHotbar2;
                @hotbar2.canceled += instance.OnHotbar2;
                @hotbar3.started += instance.OnHotbar3;
                @hotbar3.performed += instance.OnHotbar3;
                @hotbar3.canceled += instance.OnHotbar3;
                @hotbar4.started += instance.OnHotbar4;
                @hotbar4.performed += instance.OnHotbar4;
                @hotbar4.canceled += instance.OnHotbar4;
                @hotbar5.started += instance.OnHotbar5;
                @hotbar5.performed += instance.OnHotbar5;
                @hotbar5.canceled += instance.OnHotbar5;
                @hotbar6.started += instance.OnHotbar6;
                @hotbar6.performed += instance.OnHotbar6;
                @hotbar6.canceled += instance.OnHotbar6;
                @hotbar7.started += instance.OnHotbar7;
                @hotbar7.performed += instance.OnHotbar7;
                @hotbar7.canceled += instance.OnHotbar7;
                @hotbar8.started += instance.OnHotbar8;
                @hotbar8.performed += instance.OnHotbar8;
                @hotbar8.canceled += instance.OnHotbar8;
                @hotbar9.started += instance.OnHotbar9;
                @hotbar9.performed += instance.OnHotbar9;
                @hotbar9.canceled += instance.OnHotbar9;
                @mousewheel.started += instance.OnMousewheel;
                @mousewheel.performed += instance.OnMousewheel;
                @mousewheel.canceled += instance.OnMousewheel;
                @useitem.started += instance.OnUseitem;
                @useitem.performed += instance.OnUseitem;
                @useitem.canceled += instance.OnUseitem;
            }
        }
    }
    public PlayerActions @player => new PlayerActions(this);
    public interface IPlayerActions
    {
        void OnHotbar1(InputAction.CallbackContext context);
        void OnHotbar2(InputAction.CallbackContext context);
        void OnHotbar3(InputAction.CallbackContext context);
        void OnHotbar4(InputAction.CallbackContext context);
        void OnHotbar5(InputAction.CallbackContext context);
        void OnHotbar6(InputAction.CallbackContext context);
        void OnHotbar7(InputAction.CallbackContext context);
        void OnHotbar8(InputAction.CallbackContext context);
        void OnHotbar9(InputAction.CallbackContext context);
        void OnMousewheel(InputAction.CallbackContext context);
        void OnUseitem(InputAction.CallbackContext context);
    }
}
